FROM ubuntu:14.04

RUN apt-get update -y && \
    apt-get install -y \
    git \ 
    haskell-platform

RUN git clone https://github.com/JacopoTeneggi/data-science-studies.git /hxlmath && cd /hxlmath && git checkout hxlmath